version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:current

    steps:
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
      - checkout
      - store_artifacts:
          path: ./test_data/selenium
          destination: report.json
  

workflows:
  say-hello-workflow: 
    jobs:
      - say-hello
